### ISSUE TITLE
透明度问题

### ISSUE THREAD

**Issue by 429329513wanting** [seedotlee/AlipayIndexDemo#1]
来回连续上下拖动，透明度处理那块有问题，该显示的没显示，改隐藏的没隐藏，不知道怎么解决

**Comment by seedotlee** [comment]
我无法复现这个问题啊，你拉取的是最新的代码么？

**Comment by comcuter** [comment]
@seedotlee  

这个 bug 在真机上不容易复现, 在模拟器上比较容易复现.

复现的办法就是先把页面往上滑动,直到 tableView 在导航栏下方, 然后再**迅速**地向下滑动页面. 就会导致中间的几个大按钮没有显示. 偶尔会出现半透明的状态. 

原因是: 滑动太快时,  `scrollViewDidScroll:` 每次回调时 contentOffset 会相差比较大, 所以最后一次进入 `y < functionHeaderViewHeight && y > 0` 这个条件的 y 会比零大很多, 所以就会出现透明度不对的问题. 我改了下, 在 `y < 0` 时, 重置下几个 view 的 alpha, 然后就可以了.
