### ISSUE TITLE
下拉刷新的时候如果只下拉一点点,  之后就没办法收回去的哦

### ISSUE THREAD

**Issue by lmd00071** [seedotlee/AlipayIndexDemo#4]

**Comment by lmd00071** [comment]
如果下拉到能刷新的程度的话是可以自动收回去的,  但是只是简单拉一下就不行了

**Comment by seedotlee** [comment]
你说的是下拉刷新的控件？我测试是没有你描述的这个问题的，这个demo为了简单用的是MJRefresh，如果有问题应该是它的bug，这个完全可以自己写一个简单的或者使用其他的下拉刷新控件。

**Comment by lmd00071** [comment]
我刚刚试了一下, 你的demo确实没问题,  应该 是我的问题, 我自定义cell之后就出现这个很奇怪问题了

**Comment by lmd00071** [comment]
刚刚发现不是cell的问题, 是隐藏导航栏之后的问题, 你的demo没有导航栏, 所以没有出现这个问题

**Comment by lmd00071** [comment]
问题已解决self.automaticallyAdjustsScrollViewInsets = true  关闭这个就行
